version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: db-dev
    ports:
        - 5432:5432
    volumes:
        - postgres:/var/lib/postgresql/data
    environment:
        - POSTGRES_PASSWORD=password
        - POSTGRES_USER=root
        - POSTGRES_DB=db-dev
volumes:
    postgres:
        name: db-dev